csskit: Resolve platform binary using a directory walk, fixing `npx`. (#771)
Currently `npx csskit@0.0.11` is broken. Running this on my mac I get:

```
Error: csskit binary not found for darwin-arm64
Please ensure the appropriate platform package is installed:
  npm install csskit-darwin-arm64
```

The problem is that `npx` will install dependencies "flat". We assume
that the
binary is located in `csskit`'s `node_modules` directory, but that isn't
the
case here. For example `npm i -g csskit` will install:

- `/Users/<...>/node_modules/csskit/bin/csskit`
-
`/Users/<...>/node_modules/csskit/node_modules/csskit-darwin-arm64/bin/csskit`

While `npx csskit` installs:

- `/Users/<...>/node_modules/csskit/bin/csskit`
- `/Users/<...>/node_modules/csskit-darwin-arm64/bin/csskit`

To fix this, this change incorporates a directory walk instead of a
single
lookup. Starting from `csskit`'s `bin` directory we check
`../node_modules/...`
to see if the package is installed there. This means we'll check for
e.g.:

-
`/Users/<...>/node_modules/csskit/node_modules/csskit-darwin-arm64/bin/csskit`
-
`/Users/<...>/node_modules/node_modules/csskit-darwin-arm64/bin/csskit`
- `/Users/<...>/node_modules/csskit-darwin-arm64/bin/csskit`
- `/Users/node_modules/csskit-darwin-arm64/bin/csskit`

This directory walk means that for the `npm i` case, the first hit is
going to
be correct - so it shouldn't take any longer to lookup in this case. For
the
`npx` case, this will likely be the second hit, and so still should take
a very
small amount of time. The continued directory walk might also help us
for other
esoteric setups, though it's not strictly necessary (though also, it
might be
tricky to add sufficient smarts to avoid these extra lookups).